openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Session API"
  description: "API for user authentication and session management"

paths:
  /session/login:
    get:
      summary: Get login page
      description: Retrieve the login page for user authentication.
      tags:
        - Authentication
      responses:
        200:
          description: Successful operation

  /session/register:
    get:
      summary: Get registration page
      description: Retrieve the registration page for new user registration.
      tags:
        - Authentication
      responses:
        200:
          description: Successful operation

    post:
      summary: Register a new user
      description: Register a new user with the provided information.
      tags:
        - Authentication
      requestBody:
        description: User registration data
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/UserRegistration"
        examples:
          userRegistration:
            value:
              firstName: "John"
              lastName: "Doe"
              email: "johndoe@example.com"
              username: "johndoe"
              password: "password123"
              role: "USER"
      responses:
        200:
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: "#/definitions/User"
        400:
          description: Bad request
        500:
          description: Internal server error

  /session/logout:
    get:
      summary: Logout user
      description: Logout the currently authenticated user.
      tags:
        - Authentication
      responses:
        200:
          description: User logged out successfully
        500:
          description: Internal server error

  /session/github:
    get:
      summary: Initiate GitHub login
      description: Initiate the GitHub login process for user authentication.
      tags:
        - Authentication
      responses:
        302:
          description: Redirect to GitHub for authentication
        500:
          description: Internal server error

  /session/github/callback:
    get:
      summary: GitHub callback
      description: Handle the callback after GitHub authentication.
      tags:
        - Authentication
      responses:
        302:
          description: Redirect to the application after GitHub authentication
        500:
          description: Internal server error

definitions:
  LoginCredentials:
    type: object
    properties:
      usernameEmail:
        type: string
      password:
        type: string

  UserRegistration:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      username:
        type: string
      password:
        type: string
      role:
        type: string

  User:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      username:
        type: string
      role:
        type: string
